[project]
name = "minidjango-wasm-example"
version = "0.0.0"
requires-python = ">=3.12"

[tool.ty.src]
exclude = [".ty"]

[tool.ty.plugins]
enabled = true

[[tool.ty.plugins.plugin]]
id = "example.minidjango"
path = ".ty/plugins/minidjango.wasm"
runtime = "wasm"
manifest-path = ".ty/plugins/minidjango.plugin.json"
trusted = true
